### ISSUE TITLE
ShapeGraph.h and BatchProcess.h file not found

### ISSUE THREAD

**Issue by cravisjan97** [ialhashim/TopoBlender#2]
I tried building TopoBlend.pro file on Windows 10 and I get ShapeGraph.h no file error on Model.h and BatchProcess.h no file error on DocumentAnalyzeWorker.cpp. Is there a fix for this?

**Comment by ialhashim** [comment]
You need to download https://github.com/ialhashim/GeoTopo this is an essential component.
