### ISSUE TITLE
Makefile.Debug errors

### ISSUE THREAD

**Issue by cravisjan97** [ialhashim/TopoBlender#4]
I am trying to build TopoBlender.pro on MingW 64 bit compiler and I get the following build errors. 

- error: /wd4522: No such file or directory
- error: /openmp: No such file or directory
- error: [Makefile.Debug:3373: debug/main.o] Error 1

Any idea why there are no file/directory errors. Where should these folders be included? Thanks in advance

**Comment by ialhashim** [comment]
I've only tested on MSVC.
